### ISSUE TITLE
代理串联支持二级代理账号密码验证吗？

### ISSUE THREAD

**Issue by 7c69395836a06d11** [bytedance/g3#105]
代理串联支持二级代理账号密码验证吗？
会不会考虑增加？例如socks5(用户认证)->socks5(用户认证)

**Comment by zh-jq-b** [comment]
是说二级代理的用户名也由客户端传递过来？

**Comment by zh-jq-b** [comment]
> 二级代理的账号和密码是预设好的，因为很多SOCKS5代理现在都需要用户名认证才可以使用

现在的proxy_socks5 escaper是支持设置用户名密码的

**Comment by zh-jq-b** [comment]
https://github.com/bytedance/g3/blob/master/g3proxy/doc/configuration/escapers/proxy_socks5.rst 这里是具体escaper的配置条目，用proxy_socks5 escaper替换掉 https://github.com/bytedance/g3/blob/master/g3proxy/examples/chain_squid/g3proxy.conf 这里的proxy_http escaper就可以了

**Comment by zh-jq-b** [comment]
> 

UDP也支持
