### ISSUE TITLE
配置文件存放路径文档不对

### ISSUE THREAD

**Issue by fuji246** [bytedance/g3#153]
> 使用发行版原生安装包安装的，已经安装了systemd参数化服务配置文件，参数就是进程组名称， 对应的入口配置文件存放路径为/etc/g3proxy/<daemon_group>/main.yml。

这里看起来应该是“/etc/<daemon_group>/main.yml”， 比如"/etc/g3proxy/simple_fwd_proxy/main.yml"

**Comment by zh-jq** [comment]
没问题，就是/etc/g3proxy/<daemon_group>/main.yml这个，/etc/g3proxy是所有daemon进程组公共目录

**Comment by fuji246** [comment]
使用发行版原生安装包安装的，已经安装了systemd参数化服务配置文件，参数就是进程组名称， 对应的入口配置文件存放路径为/etc/<daemon_group>/main.yml。
