### ISSUE TITLE
Issues with SSL interception

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#157]
I am trying to configure g3proxy to do HTTP forward proxying with SSL inspection (and ICAP adaptation).

Using the examples I found I was able to create the following config file. It will forward HTTP traffic but does not seem to do SSL interception or send ICAP adaptation requests.

It looks like you have fixed the initial g3fcgen issue I was running into. But I have found some more issues which seem to be causing failures.

**Comment by mspublic** [comment]
It looks like like the certificate generation has some issues. The certificates it is generating are using the same fingerprints/public keys for multiple websites. For example google and githubs certificates are the same. I am attaching the certificates that are output from the proxy. This issue is causing Firefox to fail on all sites with "SEC_ERROR_REUSED_ISSUER _AND_SERIAL".

<img width="1549" alt="Screenshot 2024-02-16 at 2 11 13 PM" src="https://github.com/bytedance/g3/assets/1268608/e9937069-55fb-421a-854d-3536fc38726b">
<img width="827" alt="Screenshot 2024-02-16 at 2 10 23 PM" src="https://github.com/bytedance/g3/assets/1268608/3c46ce44-235f-48f0-b535-a32a61382c84">
[github.com.pem.txt](https://github.com/bytedance/g3/files/14315668/github.com.pem.txt)
[www.google.com.pem.txt](https://github.com/bytedance/g3/files/14315670/www.google.com.pem.txt)

**Comment by zh-jq** [comment]
yes, currently g3fcgen use a single private key for all cert generation.
I will fix this after back to work.
For production usage you may want to use a custom cert generator, as long as it follows the protocol described here https://github.com/bytedance/g3/blob/master/g3proxy/doc/protocol/helper/cert_generator.rst.

**Comment by zh-jq-b** [comment]
I have updated g3fcgen to use different serial for each cert generation.
Firefox now can work with http1. I have to spend more time to investigate why h2 streams get timed out.

**Comment by zh-jq-b** [comment]
I have removed the h2 server push feature and firefox can work now with h2 enabled.

Also note the replacement feature - 103 Early Hints, which is currently not supported by the h2 crate, so you will still encounter errors if the server return 103 response.

**Comment by zh-jq-b** [comment]
> Being able to use g3fcgen would be ideal as for the long term use of the project (in production). If we compare to something like squid etc they all have the functionality built in. Being able to leverage the same code/libraries is very useful to make sure there is no conflicts on functionality/support of encryption methods etc.

The current way is just the same as squid's helper program by providing a default implementation while still make it possible to use another one if you want cert cache, or hardware acceleration or any other features.

> Is there a different cert generator that you have been using?

Yes we use another one in the initial test which bind more tightly to our infrastructure.

**Comment by mspublic** [comment]
That makes sense. I wasnt sure if there was a a better one I should be using. The fixes you made though have been working great! Thanks!

**Comment by mspublic** [comment]
Following up on this. The changes made have been working perfectly. This can be closed.

Thank you again my friend.
