### ISSUE TITLE
Feature Request: Full remote certificate inspection and duplication for TLS MITM

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#172]
Non critical Feature Request:
When doing TLS MITM the certificate provided to the client currently only has a matching SNI. In an ideal scenario the certificate provided to the client should match as many fields as possible from the remote server certificate (outside of ones such as serial etc). This may cause a small performance hit but since the code already pulls the SNI do I not believe it will be major.

Currently this is not causing major issues anywhere. But is something to keep in mind to feature match closed source proxies.

**Comment by zh-jq-b** [comment]
I'm also considering send the real server cert to cert generator and use it as a template for the generated fake cert.
One another way is to let the cert generator fetch the real server cert by itself.
And we may also need to add domain level rules in the cert generator, such like use more wildcard domain certs to allow more reuse.
It's still undecided yet.

**Comment by mspublic** [comment]
Those all sound like good options. 

I think your first idea of sending the certificate to the generator may be the best - in some cases the cert generator may be on a machine that does not have direct internet access (potentially connected to an HSM) so having the certificate provided to it would be optimal.
