### ISSUE TITLE
Allow hostnames in the config

### ISSUE THREAD

**Issue by jeffreydwalter** [bytedance/g3#180]
Hello!

I'm working with @mspublic to get g3proxy running in Docker. Currently, it's not possible to stream the udpdump traffic to Wireshark on the host machine because g3-yaml only accepts `ip:host`. In order to get this working, we need to use `host.docker.internal:5555` in the config.

If you don't mind, I have a PR that changes calls to `SocketAddr::from_str()` to `ToSocketAddrs::to_socket_addrs()` in a couple of places related to config parsing, mainly in g3-yaml.

**Comment by mspublic** [comment]
Thanks @jeffreydwalter. I think this would be useful for more than just docker - many production environments use hostnames not IPs even without docker.

**Comment by zh-jq-b** [comment]
Is it possible to use environment variables? You can set the value to `$SOME _RESOLVED_ADDR` to read from env var `SOME_RESOLVED_ADDR`.

Domains can be dynamically updated and may resolve to many IP addresses, it's not easy to add proper support.

**Comment by mspublic** [comment]
In my opinion this patch doesn’t prevent someone from doing that or using an IP. It just gives the option of using the domain instead.

**Comment by jeffreydwalter** [comment]
If there's a concern about resolving multiple ips, perhaps we could add a check to count the number of ips resolved and return an error if it's more than one?

**Comment by zh-jq** [comment]
> If there's a concern about resolving multiple ips, perhaps we could add a check to count the number of ips resolved and return an error if it's more than one?

A warning message is needed to tell the users that the domain support is only restricted to one IP address and no dynamic update will be available.

The `UpstreamAddr` type can be used for proper domain support. And we should resolve the domain just before we try to connect to the peer.
