### ISSUE TITLE
Certain sites fail to load if browser is using HTTP1 via G3proxy

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#235]
Following up from the previous panic issue I have identified certain sites that will cause the timeout that caused the panic. It seems to happen when connecting to certain sites via HTTP1 - not via HTTP2.

Reproduction steps:
1. Disable HTTP2 in your browser of choice. I am using firefox.
2. Attempt to load https://scrapfly.io/web-scraping-tools/ja3-fingerprint

[config.yml.txt](https://github.com/bytedance/g3/files/15266253/crash_config.yml.txt)

**Comment by zh-jq** [comment]
can you this in the auditor config?
```
protocol_inspection:
  data0_wait_timeout: 300s
```

**Comment by zh-jq-b** [comment]
After https://github.com/bytedance/g3/commit/1493b4d9b924c19e347736e1d7cb5b0d41525fff, the browser now POST to p.clarity.ms indefinitely, and the response is always 204 No Content

**Comment by zh-jq-b** [comment]
There are some errors when forwarding the repsonse body of the first GET request, I will fix that tomorrow.

**Comment by mspublic** [comment]
Thanks!
