### ISSUE TITLE
希望能在socks5认证时动态设置上级代理

### ISSUE THREAD

**Issue by enp6** [bytedance/g3#247]
老版本g3proxy1.8中，socks5认证过程(task.rs ServerTaskNotes)里时是支持设置json格式的egress_path_selection，这让我可以在认证信息中将上级代理的信息包含在里面并且动态设置上级代理(甚至可以动态设置每个上级代理的限速限流，这是一个非常好的方法)，但在新版本中已经改成了ID的形式并且不支持动态去设置上级代理了，希望能在未来的版本中重新支持！！！

这个项目完成度非常高，目前开源的项目中只有g3proxy那么全面！！！

**Comment by zh-jq-b** [comment]
https://github.com/bytedance/g3/commit/7c05487748241b835fdacd7f136ee7d56d75d367 可以测试验证下
