### ISSUE TITLE
steal_forwarded_for is not respected/working for http_proxy

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#248]
When setting steal_forwarded_for to true for http_proxy it does not remove the "X-Forwarded-For" headers. It appears the code to check the headers is not being hit (at least via debug statements) - https://github.com/bytedance/g3/blob/47f2cc8191a9288f14c276ad23507ea8e30b183e/g3proxy/src/serve/http_proxy/task/protocol/request.rs#L60

**Comment by zh-jq-b** [comment]
The code there will not store Forwarded header for HTTP request. I guess you want to delete the Forwarded header in HTTPS request?

**Comment by mspublic** [comment]
Yes we want to access the headers in the https requests. We are wanting to remove the downstream XFF header as it’s leaking internal IPs.

**Comment by zh-jq** [comment]
You can test it with commit d38d9d61ea6032ff4062cd4a4c4575293d9bcc6f

**Comment by mspublic** [comment]
I tested with the latest code. Unfortunately it does not seem to be working - both on HTTP1 and HTTP2.

**Comment by zh-jq-b** [comment]
Should be fixed with this commit d39770de6f27bff16bf9d2e3abeeed796933658a.

**Comment by mspublic** [comment]
Tested and working well! Thanks!!
