### ISSUE TITLE
希望能增加账号全局限速功能

### ISSUE THREAD

**Issue by enp6** [bytedance/g3#266]
希望能增加账号全局限速功能，目前依靠连接限速的方式避免不了单用户发起大量连接，依靠任务存活限制去限制连接数的话又非常影响客户体验，毕竟现在就算简单打开一个页面可能都会发起几十个连接，所以这时候全局限制带宽更加能解决问题！

**Comment by zh-jq** [comment]
进程内全局限速在1.9.6版本已支持，集群全局限速合并到 #93 处理
