### ISSUE TITLE
Authentication with a database

### ISSUE THREAD

**Issue by NinoSkopac** [bytedance/g3#286]
Dear team at Bytedance,

This seems like a promising, modern replacement for squid. 

Is there a scalable way to do auth?

I can only see putting users in a yaml file as an option, and i can't find docs to clarify the concept either. 

Squid does this quite neatly: https://wiki.squid-cache.org/ConfigExamples/Authenticate/Mysql

Regards and thank you.

**Comment by zh-jq** [comment]
The configuration doc is here https://github.com/bytedance/g3/tree/master/g3proxy/doc.
It's possible to fetch dynamic users from DB by using lua/python script as a `source` config in https://github.com/bytedance/g3/blob/master/g3proxy/doc/configuration/user_group/index.rst.

**Comment by NinoSkopac** [comment]
Awesome Mr. Jingqiang, thank you so much for this extremely timely and precise answer. 

I'm going to embark on an adventure of setting this up and if i like it I'll be running hundreds of these in production. ( In k8s. )

I'm coming from squid because of its high ram usage - 150mb at minimum. I haven't run this yet, but I hope the memory consumption will be much lower. 

Regards and thank you
