### ISSUE TITLE
Feature request: periodic log entries during large file transfers

### ISSUE THREAD

**Issue by NinoSkopac** [bytedance/g3#294]
When downloading large files (e.g., a 1TB file), it would be helpful to receive periodic log entries at defined intervals (e.g., every n seconds) that report on the progress of the file transfer. Instead of a single log entry at the end indicating the completion of the transfer, the system should generate multiple log entries during the transfer, each corresponding to a specific chunk of data delivered.

This feature would provide real-time visibility into the progress of large file transfers, making it easier to monitor and manage the download process, especially in environments where continuous feedback is crucial.

Totally fine if this is behind a flag.

Thank you and have a great day!

**Comment by zh-jq-b** [comment]
Do you want this feature just for layer-7 HTTP request/response, or for all of the layer-4 tunnel connections?

**Comment by NinoSkopac** [comment]
Layer 4, please. I do love having socks5, it's so much more efficient. In my tests it consumes way less data for the same URL compared to http proxy.

Thank you Mr. Zhang!!!

**Comment by zh-jq** [comment]
For tunnel connections, we don't known whether it's downloading files. What can be done is that, log when reading/writing to client connections at some nearly fixed time interval.

**Comment by NinoSkopac** [comment]
That works!

**Comment by NinoSkopac** [comment]
Note: auth and its refresh interval must be respected. As in, a user could be valid now, but invalid at a later chunk/interval. In that case the connection must be terminated.

**Comment by zh-jq-b** [comment]
> Note: auth and its refresh interval must be respected. As in, a user could be valid now, but invalid at a later chunk/interval. In that case the connection must be terminated.
> 
> Should this be a separate issue? Is this already implemented? (I haven't tested.)

You can set a user to blocked state and then it will be blocked after `idle_check_interval` (5min by default).

**Comment by zh-jq-b** [comment]
The enovy way: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging#periodic-access-logs.
The plan is to add a `task_log_flush_interval` and `task_log_on_stage_change` config options in server config, and just do task log at that `flush interval` or when task stage changed (new -> connected -> relay).
@NinoSkopac does this work for you?

**Comment by NinoSkopac** [comment]
Sounds good. 

I guess for my particular use case I only need to use `task_log_flush_interval`?
