### ISSUE TITLE
How to auditor based on domain?

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#311]
I am trying to determine the best way to choose an escaper based on domain. For instance if a connection is going to google.com I would like them to goto one auditor but if its yahoo.com goto a different auditor.

Thanks!

**Comment by zh-jq-b** [comment]
I will add an optional `auditor` config option in escaper config, and it will overwrite the server side `auditor` config if present.

**Comment by mspublic** [comment]
One of the uses for this is so we can configure what sites are sent to icap/etc.

**Comment by mspublic** [comment]
Thanks!
