### ISSUE TITLE
Feature Request: Bind Interface

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#316]
A nice feature to have would able to have a "bind_interface" config flag - similar to bind_ip. This would allow the proxy to be able to load without needing to know it's IP in the config. Example:

`bind_interface: eth0`

**Comment by zh-jq** [comment]
Which type of escaper do you want to set a bind interface?

**Comment by mspublic** [comment]
I think at a practical level it would be the same places that have bind_ip in the config. This just gives the option of selecting based on network interface as opposed ip.

**Comment by mspublic** [comment]
Thanks!!
