### ISSUE TITLE
Clarifications regarding server request metrics

### ISSUE THREAD

**Issue by zhilingc** [bytedance/g3#322]
I'd like to clarify the meaning behind `server.task.total` and `server.task.alive` --

* Is `server.task.total` the total number of requests serviced by the server? The docs mention "Each client connection will be promoted to task only if the negotiation success.", but this value is, as far as I can tell, not the number of client connections accepted by the server, since this value is different from `listen.accepted` even with no authentication in place. 
* Similarly, is `server.task.alive` the number of requests currently being serviced by the server? In my current setup, this value is very high -- for reference, server.task.total has a rate increase of around 700-800, and server.task.alive is around 12k. Each request takes around 120ms as recorded by the upstream application
* In my testing, server.task.total did correspond to the total number of requests, but this was without connection pooling

The upshot is, I'm looking for a measurement of the number of requests relayed by the proxy over time (or QPS). Do any of these two metrics fulfil that requirement? 

Thanks in advance, and apologies if this is already explained in the docs.

**Comment by zh-jq-b** [comment]
> * Is `server.task.total` the total number of requests serviced by the server?

Yes, the requests here is proxy requests which may be http_forward, http_connect, socks_connect. The user level request metrics will contain an extra `request` tag to show the real proxy request type.

> The docs mention "Each client connection will be promoted to task only if the negotiation success.", but this value is, as far as I can tell, not the number of client connections accepted by the server, since this value is different from `listen.accepted` even with no authentication in place.

No. 'server.connection.total' is like `listen.accepted` if all connections can be authenticated successfully. You may send several proxy requests in one single connection.

> * Similarly, is `server.task.alive` the number of requests currently being serviced by the server?

Yes, the task here is also valid proxy requests.

> In my current setup, this value is very high -- for reference, server.task.total has a rate increase of around 700-800, and server.task.alive is around 12k. Each request takes around 120ms as recorded by the upstream application

For https requests, in which case the client will send HTTP CONNECT request, the alive task here is actually the count of alive connections, which may not get closed after client received the HTTP response, and thus live longer.

> The upshot is, I'm looking for a measurement of the number of requests relayed by the proxy over time (or QPS). Do any of these two metrics fulfil that requirement?

The rate of `server.task.total` is the RPS of proxy requests.
To see the rate of each specific proxy request type, you need to setup a user group with anonymous user enabled and then use the rate of `user.request.total` with the corresponding `request` tag set. This way you can see the RPS for plain HTTP traffic.
Currently we didn't support layer 7 http request metrics in audit code if TLS interception is used, but this may be implemented if needed.

**Comment by zhilingc** [comment]
Ah, gotcha. This is really helpful. Amazing project by the way, its been a real gamechanger for me 🙏
