### ISSUE TITLE
ICAP egress traffic hardcodes transfer-encoding chunked

### ISSUE THREAD

**Issue by GlenDC** [bytedance/g3#390]
The current ICAP logic enforced transfer encoding "chunked" for egress traffic. This can cause problems with servers that only work with non-chunked bodies (content-length).

The ICAP module should, I think, respect the original encoding. According to the RFC (3507) chunked encoding is indeed the way to go for the ICAP traffic, but the proxy itself should translate it back to a content-length body if that is what the http header defines.

This might be an easy fix for you if you agree as you probably know best what needs to change. However if you do not have the bandwidth but do agree, do feel free to push me in the right direction with some guidelines and I can see to contribute it myself.

In case I miss something here or have wrong assumptions please do let me know as well.

**Comment by zh-jq-b** [comment]
> The current ICAP logic enforced transfer encoding "chunked" for egress traffic. This can cause problems with servers that only work with non-chunked bodies (content-length).
> 
> The ICAP module should, I think, respect the original encoding. According to the RFC (3507) chunked encoding is indeed the way to go for the ICAP traffic, but the proxy itself should translate it back to a content-length body if that is what the http header defines.

Yes it will be better if the original encoding could be used.

The logic could be:

For http/1, if the ICAP server send back a modified request/response with `Content-Length` set in HTTP header, decode the body then send to upstream. If no `Content-Length` header found, add `Transfer-encoding: chunked` to the header and send the encoded body directly to upstream.
For http/2, just keep the `Content-Length` header as there in the header sent to upstream.

> 
> This might be an easy fix for you if you agree as you probably know best what needs to change. However if you do not have the bandwidth but do agree, do feel free to push me in the right direction with some guidelines and I can see to contribute it myself.
> 
> In case I miss something here or have wrong assumptions please do let me know as well.

It seems to be easy to add the code, I will submit a PR first for it.

I'm not sure whether httpbin.org can support such testcases, can you help to add a test conf in `scripts/coverage/g3proxy`?

**Comment by zh-jq-b** [comment]
#391 now contains the first commit for REQMOD

**Comment by zh-jq-b** [comment]
The coverage data in #391 seems already cover the new added logic. So I will merge it first and then add chunked response test case later.

**Comment by GlenDC** [comment]
Thanks @zh-jq-b , do let me know if you need me for anything regarding this. Take care.
