### ISSUE TITLE
Request: Possible to include a curl test command with each of the g3proxy examples

### ISSUE THREAD

**Issue by webhype** [bytedance/g3#405]
The examples are bare bones, to say the least, there is no documentation whatsoever what these examples are supposed to do and how to test if they work.

When I run the first one, proxy chain, I assume a sane way to test this would be the following command:
```
$ curl -x http://localhost:3128 https://icanhazip.com
curl: (56) CONNECT tunnel failed, response 504
```

Would it be possible to include a README.md with each example, or even simpler, to add `#` comments into the `.yaml` files so it's a bit clearer what's supposed to happen there and how to customize it for our use case?

**Comment by zh-jq** [comment]
> The examples are bare bones, to say the least, there is no documentation whatsoever what these examples are supposed to do and how to test if they work.

You can find test commands used in the coverage testcases here https://github.com/bytedance/g3/tree/master/scripts/coverage/g3proxy.

> 
> When I run the first one, proxy chain, I assume a sane way to test this would be the following command:
> 
> ```
> $ curl -x http://localhost:3128 https://icanhazip.com
> curl: (56) CONNECT tunnel failed, response 504
> ```
> 

The proxy returned a 504 response for the HTTP CONNECT request,
you can set `log: stdout` in the config to see the error logs.

> Would it be possible to include a README.md with each example, or even simpler, to add `#` comments into the `.yaml` files so it's a bit clearer what's supposed to happen there and how to customize it for our use case?

It will but that will take a long time as we don't have enough time to improve the documentation currently.
You can also check the user guide here in this directory https://github.com/bytedance/g3/tree/master/g3proxy.

**Comment by webhype** [comment]
Thanks for the fast response, the issue was `resolver`, which is the DNS resolver and setting it to 8.8.8.8 (Google's DNS) made it work instantly, thanks! Thanks for the link to the test cases, very helpful.
