### ISSUE TITLE
可删除此issues，已自魔改~

### ISSUE THREAD

**Issue by enp6** [bytedance/g3#45]
可删除此issues，已自魔改~

**Comment by zh-jq** [comment]
用户这块，目前用户组user-group下面可以配置2种用户：
1、静态用户，从配置文件加载，优先匹配
2、动态用户，可以使用lua/python脚本定时从控制中心获取全量列表
动态用户的变更是否可以考虑在控制中心实现？API在控制中心进行支持即可

用户维度的配置中，目前不支持配置bind IP及下一跳代理地址，如果这些配置比较明确，可以考虑：
1、为每一个bind IP+代理地址配置一个 ProxyXX Escaper，这样每一个出口方式都会有独立的监控（用户监控下也有Esccaper tag的出口监控）
2、为支持各种场景灵活定义出口选择策略，提供了RouteQuery Escaper,该出口配置支持通过另一个Agent进行下一跳Escaper查询（可以用户名+目标访问地址+客户端IP），可以开发独立的Agent来做灵活的出口选路逻辑

以上是否能支持当前的需求？
